### ISSUE TITLE
Java heap space out of memory when sending/receiving

### ISSUE THREAD

**Issue by GrachiCP** [kyamagu/matlab-tcpip#1]
When the sending or receiving information that is bigger than the available Java Heap Space you get:

> java.lang.OutOfMemoryError: Java heap space

When a java method is called in Matlab, the data is copied to the java heap space. This is a limitation when data is too big.

Maybe changing the implementation of Input/OutputStream read/write to a buffered version to avoid this problem.

**Comment by kyamagu** [comment]
@GrachiCP Thanks for reporting this. Will check the buffered alternative (or pull-request me).

**Comment by kyamagu** [comment]
@GrachiCP The latest commit should resolve the out-of-memory issue. It was a bit tricky to workaround Matlab's automatic byte conversion.
